def -params 1 -docstring "colorscheme <name>: enable named colorscheme" \
    -shell-script-candidates %{
    find -L "${kak_runtime}/colors" "${kak_config}/colors" -type f -name '*\.kak' \
        | while read -r filename; do
            basename="${filename##*/}"
            printf %s\\n "${basename%.*}"
        done | sort -u
  } \
  colorscheme %{ evaluate-commands %sh{
    find_colorscheme() {
        find -L "${1}" -type f -name "${2}".kak | head -n 1
    }

    filename=""
    if [ -d "${kak_config}/colors" ]; then
        filename=$(find_colorscheme "${kak_config}/colors" "${1}")
    fi
    if [ -z "${filename}" ]; then
        filename=$(find_colorscheme "${kak_runtime}/colors" "${1}")
    fi

    if [ -n "${filename}" ]; then
        printf 'source %%{%s}' "${filename}"
    else
        echo "fail 'No such colorscheme ${1}.kak'"
    fi
}}

declare-option str kak_no_autoload nop

evaluate-commands %sh{
    echo "colorscheme default"

    {
        find -H "${kak_runtime}/autoload" -type f -name '*.kak'
        if [ -d "${kak_config}/autoload" ]; then
            find -L "${kak_config}/autoload" -type f -name '*.kak' | xargs realpath |
                grep -v "^$(realpath "${kak_runtime}/autoload" | sed 's/[.^$*\[\\]/\\&/g')" # Skip obsolete links into runtime autoload.
        fi
    } | sed 's/.*/try %{ source "&" } catch %{ echo -debug Autoload: could not load "&" }/'

    if [ -f "${kak_runtime}/kakrc.local" ]; then
        echo "source '${kak_runtime}/kakrc.local'"
    fi

    if [ -f "${kak_config}/kakrc" ]; then
        echo "source '${kak_config}/kakrc'"
    fi
}
